version: '3'
services:
  app:
    container_name: api
    volumes:
      - .:/app
    restart: always
    image: sonikuc/distribuidos-3b
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4-focal
    restart: always 
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: "/data/gv0/vols/distribuidos-3b"
        target: "/my/own/api"
volumes:
  mongo-data:
